### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by quintenbuijs2006** [alikkon/tametheark#1]
Hi i am getting a 502 bad gateway

**Comment by alikkon** [comment]
I need more details to help troubleshoot please.
What web server software are you using? (Apache Webserver, LightHTTPD, NginX, Apache Apache Traffic Server, Microsoft's Webserver, Mozilla Webserver for Windows, etc...)
Do you have a layer between the client and webserver, such as Cloudflare?
What versions of Apache and PHP are you running?
What Linux distro are you running? I've mostly done testing under RedHat derivatives such as CentOS and Fedora, but can do some testing with alternative distros to help find your issue.
Are you seeing any error messages in your webserver logs related to the 502 bad gateway errors?

**Comment by quintenbuijs2006** [comment]
I tried nginx and apache and i run on a ubuntu 22.04 virtual machine on my windows device.

**Comment by alikkon** [comment]
> 502 Bad Gateway
> The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.Sep 12, 2022
> 502 Bad Gateway - HTTP - MDN Web Docs
> https://developer.mozilla.org 

After creating an Ubuntu 22.04 instance, installing apache2, php, libapache2-mod-php, and configuring ufw to allow 'Apache Full', I'm unable to reproduce your 502 error. This does not appear to be a bug, but is likely with the configuration of your host, gateway, firewall, or port forwarding tools.

While the setup.sh script does a lot of work for the user, remember that the last step isn't completed by the setup.sh script - it states this when you finish running it. You still need to configure your web server to point to the tool, since I can't account for configurations across all Linux distributions. 

> +------------------------------------------------------------+
> |    Tame The Ark files configuration has been completed.    |
> |    If you have not already you will need to configure      |
> |    your apache virtualhost.                                |
> +------------------------------------------------------------+

I'd be happy to help you figure out your webserver configuration, but I don't believe you've found a bug.

**Comment by alikkon** [comment]
As an example, my ubuntu host (which does not use authentication, since it was simply to test this bug, and runs as the root on the webserver rather than a subdirectory) is configured using the following:

File: /etc/apache2/sites-available/tametheark.conf
> DocumentRoot /var/www/tametheark/www
> <Directory /var/www/tametheark>
>     DirectoryIndex index.html index.php
>     AllowOverride None
>     Require all granted
> </Directory>

I removed the preexisting files under /etc/apache2/sites-enabled, then symlinked using:
> sudo ln -s /etc/apache2/sites-available/tametheark.conf sites-enabled/tametheark.conf

You may need to adjust if running in a subdirectory or using digest authentication. If you want to use Steam-based authentication, you'll need to update ${tametheark}/conf/conf.php and add your steam_ids using:
> steam_ids[] = numeric_steam_id

**Comment by quintenbuijs2006** [comment]
I tried to reinstall it on another operating system. But i dont know what to put on rsync

**Comment by alikkon** [comment]
You may not have the rsync package installed - the script tries to detect it, but if it's not installed it will leave it blank by default. You could probably modify the script to work without rsync if you wanted to instead, since it's only used for making backups before updating, but installing the package shouldn't contain any risk.

`apt install rsync` should do the job, then just run the setup script again.

**Comment by quintenbuijs2006** [comment]
Still getting the same error. In Nginx i change the / location to /root/tametheark/www

**Comment by alikkon** [comment]
To be clear, I have not tested this at all with Nginx - only with Apache 2.x server. With Nginx, you'll probably need to enable php-fpm and possibly other modules to make it work. At this time, I don't guarantee it will work with anything other than Apache 2.x - which is stated in the Readme for the tool. For my own Ubuntu testing, I did the following:

Downloaded an Ubuntu 22.04 ISO
Started up my virtualization software
"inserted" the ISO into my VM and installed the OS from it.
Installed the packages apache2, php, libapache2-mod-php
Configured ufw to allow traffic via "Apache Full" (this allows port 80 and 443 traffic to your host)
Configured /etc/apache2/sites-available/tametheark.conf as above
Symlinked to that file from /etc/apache2/sites-enabled/tametheark.conf
Restarted apache.

502 errors, specifically, are gateway errors, not application errors. It means your web server is trying to get traffic from somewhere else and is failing. I suspect for any additional help figuring out what's wrong with your configuration I'd need to see related config files and possibly related log entries from your application.

**Comment by alikkon** [comment]
With no new replies, and the problem seeming to be related to the specific machine (I can't reproduce it at all using the same OS version, and have not planned to use this with nginx, but it does work with apache) I'm going to resolve this issue out for now. I'm happy to talk through issues users are having, but this is not a bug.
